"""
Persistent story state for Format 2 — Serialized Thriller.
Stores the entire 7-part story arc generated by Gemini.
"""
import json
import os
import uuid
from datetime import datetime, timezone
from config import TEMP_DIR, STORY_STATE_FILE

COMPLETED_STORIES_FILE = os.path.join(TEMP_DIR, "../memory/completed_stories.json")

_DEFAULT_STATE = {
    "story_id": None,
    "story_title": None,
    "story_premise": None,
    "total_parts": 7,
    "current_part": 1,
    "parts_scripts": [],
    "parts_posted": [],
    "story_complete": False,
    "story_abandoned": False,
    "created_at": None,
    "last_updated": None
}

def load_state() -> dict:
    if not os.path.exists(STORY_STATE_FILE):
        return dict(_DEFAULT_STATE)
    try:
        with open(STORY_STATE_FILE, "r") as f:
            state = json.load(f)
            for k, v in _DEFAULT_STATE.items():
                state.setdefault(k, v)
            return state
    except Exception:
        return dict(_DEFAULT_STATE)

def save_state(data: dict):
    data["last_updated"] = datetime.now(timezone.utc).isoformat()
    os.makedirs(os.path.dirname(STORY_STATE_FILE), exist_ok=True)
    with open(STORY_STATE_FILE, "w") as f:
        json.dump(data, f, indent=4)
    print(f"💾 Story state saved (Part {data.get('current_part', '?')} / {data.get('total_parts', 7)})")

def reset_state():
    save_state(dict(_DEFAULT_STATE))

def is_story_abandoned(state: dict) -> bool:
    if state["story_complete"] or state["story_abandoned"]:
        return True
    if not state["created_at"]:
        return False
    try:
        created = datetime.fromisoformat(state["created_at"])
        now = datetime.now(timezone.utc)
        if (now - created).days > 14:
            return True
    except Exception:
        pass
    return False

def archive_completed_story(state: dict):
    os.makedirs(os.path.dirname(COMPLETED_STORIES_FILE), exist_ok=True)
    completed = []
    if os.path.exists(COMPLETED_STORIES_FILE):
        try:
            with open(COMPLETED_STORIES_FILE, "r") as f:
                completed = json.load(f)
        except:
            pass
    completed.append(state)
    with open(COMPLETED_STORIES_FILE, "w") as f:
        json.dump(completed, f, indent=4)
    print("📁 Story archived to completed_stories.json")

def start_new_story(script_data: dict) -> dict:
    state = dict(_DEFAULT_STATE)
    state["story_id"] = str(uuid.uuid4())
    state["story_title"] = script_data.get("story_title", "Untitled Thriller")
    state["story_premise"] = script_data.get("story_premise", "")
    state["total_parts"] = script_data.get("total_parts", 7)
    state["current_part"] = 1
    state["parts_scripts"] = script_data.get("parts", [])
    state["parts_posted"] = [False] * state["total_parts"]
    state["story_complete"] = False
    state["story_abandoned"] = False
    state["created_at"] = datetime.now(timezone.utc).isoformat()
    return state
